name: Eduardo Muniz
favicon: null
layout_spectrum: 0.05407
typography_spectrum: 0.4458253006450832
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5431310175918043
  lightness: 0.5805103466846049
  saturation: 0.7260775952599943
  rhythmicContrast: 0.7160613045562059
purpose: []
